version: '3.4'
services:
  dbmon-es:
    image: docker-repos:8123/victoria/elasticsearch:7.6.2
    volumes:
      - "/opt/deploy/dbmon/dbmon-data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms512m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    logging:
      options:
        max-size: 10m

  dbmon-kibana:
    image: docker-repos:8123/victoria/kibana:7.6.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://dbmon-es:9200
    depends_on:
      - dbmon-es
    logging:
      options:
        max-size: 10m
